# Generated by Django 5.1.1 on 2024-09-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
