# Generated by Django 5.1.1 on 2024-09-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='post_code',
            field=models.CharField(max_length=100),
        ),
    ]
