# Generated by Django 5.1.1 on 2024-09-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_worker_post_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='post_code',
            new_name='telephone',
        ),
    ]
