# Generated by Django 5.1.1 on 2024-09-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_location_alter_worker_telephone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
