# Generated by Django 5.1.1 on 2024-09-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('agency', 'Agency'), ('dom', 'Domestic')], default='worker', max_length=10),
        ),
    ]
